name: kol_miner
description: Flutter app to mine gold in kol
version: 1.1.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  # for network calls
  http: ^0.13.3
  #to store accounts :(
  shared_preferences: ^2.0.8
  # to modify the app launcher icon
  flutter_launcher_icons: "^0.9.2"
  # for login page username dropdown
  autocomplete_textfield: ^1.7.3
  # to launch kol website
  url_launcher: ^6.0.12
  # to format numbers with commas (or periods)
  intl: ^0.17.0
  html: ^0.15.0
  universal_html: ^2.0.8
  provider: ^6.0.1            #tests

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  build_runner: ^2.1.2
  test: '>=1.17.10 <2.0.0'
# https://pub.dartlang.org/packages/flutter_launcher_icons
# must call `flutter pub pub run flutter_launcher_icons:main` for this to run
flutter_icons:
  android: true
  ios: true
  image_path: "images/miner.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
